import logo from './logo/logo.svg'
import buttonClose from './icons/ButtonClose.svg'
import events from './icons/events.svg'
import analytics from './icons/analytics.svg'
import clock from './icons/clock.svg'
import adminCenter from './icons/adminCenter.svg'
import arrowDown from './icons/arrowDown.svg'
import arrowClose from './icons/ButtonClose.svg'
import plus from './icons/plus.svg'
import shape from './pagesImage/shape.svg'
import speaker from './pagesImage/speaker.svg'
import progressbar from './pagesImage/progressbar.svg'
import calendly from './pagesImage/calendly.svg'
import calender from './icons/calenderblank.svg'
import world from './icons/world.svg'
import arrowLeft from './icons/arrowleft.svg'
import userIcon from './icons/user.svg'


export {logo,buttonClose,events,analytics,clock,adminCenter,arrowDown,arrowClose,plus,shape,speaker,progressbar,calendly,calender,world,arrowLeft,userIcon}